### ISSUE TITLE
Be explicit about only supporting Posix.

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/applications-superstaq#44]
i guess other than these lines i don't see any obvious reason why the clients wouldn't work as they are, but yeah we'd definitely need to test it. i'd be a little surprised if no one has run a demo/example notebook on windows already

definitely getting outside the scope of this PR though. meanwhile, if we're going to make it explicitly posix-only we should maybe just update setup.py to reflect that?

_Originally posted by @richrines1 in https://github.com/SupertechLabs/applications-superstaq/pull/43#discussion_r844443173_

**Comment by vtomole** [comment]
We support Windows now.

**Comment by singular-value** [comment]
![billgates](https://user-images.githubusercontent.com/3976048/177908467-fa2f6a7c-8a83-4651-9aa0-7144a1c4dff5.gif)
