### ISSUE TITLE
Check Github Actions for Windows

### ISSUE THREAD

**Issue by stephanielee9** [SupertechLabs/applications-superstaq#46]
Check for Windows Github Actions support across cirq-superstaq, qiskit-superstaq, applications-superstaq

**Comment by PalashGoiporia** [comment]
qss doesn't install properly on windows. It needs Microsoft C++ build tools.

"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

Full log in image below
<img width="652" alt="qss_windows_installation_error" src="https://user-images.githubusercontent.com/44248089/167661034-3de636d6-ac29-4423-894a-b998b6cf4758.png">

**Comment by PalashGoiporia** [comment]
Addressed by #57 #58
