### ISSUE TITLE
less specific requirements

### ISSUE THREAD

**Issue by richrines1** [SupertechLabs/applications-superstaq#8]
* `qubovert==1.2.3` should be `qubovert>=1.2.3` as in cirq_superstaq
* `numpy` requirement should be less specific. Currently cirq requires `numpy~=1.16` and qiskit requires `numpy>=1.17` - do we need 1.20?

**Comment by vtomole** [comment]
Very good point. This is something I've been meaning to raise for a while: Loosening the requirements leaves us better off. We started pining specific versions and it snowballed.

**Comment by vtomole** [comment]
> qubovert==1.2.3 should be qubovert>=1.2.3 as in cirq_superstaq

This is done.

> numpy requirement should be less specific. Currently cirq requires numpy~=1.16 and qiskit requires numpy>=1.17 - do we need 1.20?

We currently inherit qubovert's numpy version.
