### ISSUE TITLE
Add an example notebooks for `.resource_estimate` in css and qss

### ISSUE THREAD

**Issue by vtomole** [SupertechLabs/applications-superstaq#89]

**Comment by paaige** [comment]
[#295](https://github.com/SupertechLabs/cirq-superstaq/pull/295)

**Comment by paaige** [comment]
[#194](https://github.com/SupertechLabs/qiskit-superstaq/pull/194#issuecomment-1181576583) qss

**Comment by paaige** [comment]
Closing because related PRs were merged (can't link because cross-linking across different repos doesn't seem possible?). Linked in comments.
